# Sentiment Sentences

### Libs

In [ ]:
import pandas as pd
import numpy as np

### Dataset 1

In [ ]:
df1 = pd.read_csv('datasets/sentences/darija_ara_sentences.csv')
print(df1.shape)
df1.head()

(52524, 1)

                              darija_ar
0      هوما مخبّين شي حاجة, أنا متيقّن!
1    باينا هوما تايحاولو إبقاو مبرّدين.
2  لوطيلات مابايناش فيهوم مريحين بزّاف.
3         غالبا غايجرّيو عليه من لخدمة!
4                      طبعا راه مكتاءب!

In [ ]:
df2 = pd.read_csv('datasets/sentences/fr-Ar.csv')
print(df2.shape)
df2.head(10)

(8401, 3)

     ID                                               Feed Sentiment
0   1.0  m3alem bourjilia w illi ma yefehmouch yelzmou ...  Positive
1   2.0                                        Ya m3alllam  Positive
2   3.0                      Ma7lek! Zin ou fannena 7loua.  Positive
3   4.0                     hhhhh ya bliiiiiiiida ya Hanen  Negative
4   5.0                           Nikraha w ma5yebha pffff  Negative
5   6.0                                      3sal denya :*  Positive
6   7.0  سي جلول يعطيك ألف صحة و ربي يبارك فيك وكأنك شر...  Positive
7   8.0                     Ya mama mali masta lasta :p :p  Negative
8   9.0                                 Bravo Neji jelloul  Positive
9  10.0                                نسحو يفهم في كل شيء  Positive

In [ ]:
# Sort df2 by the 'Feed' column
df2_sorted = df2[['Feed', 'Sentiment']].sort_values(by='Feed')

# Select instances from index 4616 to 8380 (inclusive)
df2_selected = df2_sorted.iloc[4616:8381]

In [ ]:
print(df2_selected.shape)
df2_selected.head()

(3765, 2)

                                                   Feed Sentiment
215   أحسن الممثلات في تونس bravo wajiha et bon cont...  Positive
239          أحسن حاجة عملها سامي الفهري حاجة متوقعة \r  Positive
7004  أحسن كوميدي تونسي الكوميدية متاعو تدخل للقلب ب...  Positive
8291  أحسن كوميدي تونسي الكوميدية متاعو تدخل للقلب ب...  Positive
1416  أحسن كوميدي تونسي و تفدليكو يدخل للقلب فييسع ....  Positive

In [ ]:
df1['Sentiment'] = np.NaN
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52524 entries, 0 to 52523
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   darija_ar  52524 non-null  object
 1   Sentiment  0 non-null      float64
dtypes: float64(1), object(1)
memory usage: 820.8+ KB

In [ ]:
df2_selected.rename(columns={'Feed': 'darija_ar'}, inplace=True)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_22844\3176011792.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_selected.rename(columns={'Feed': 'darija_ar'}, inplace=True)

In [ ]:
print(df1.head())
print(df2_selected.head())

                              darija_ar  Sentiment
0      هوما مخبّين شي حاجة, أنا متيقّن!        NaN
1    باينا هوما تايحاولو إبقاو مبرّدين.        NaN
2  لوطيلات مابايناش فيهوم مريحين بزّاف.        NaN
3         غالبا غايجرّيو عليه من لخدمة!        NaN
4                      طبعا راه مكتاءب!        NaN
                                              darija_ar Sentiment
215   أحسن الممثلات في تونس bravo wajiha et bon cont...  Positive
239          أحسن حاجة عملها سامي الفهري حاجة متوقعة \r  Positive
7004  أحسن كوميدي تونسي الكوميدية متاعو تدخل للقلب ب...  Positive
8291  أحسن كوميدي تونسي الكوميدية متاعو تدخل للقلب ب...  Positive
1416  أحسن كوميدي تونسي و تفدليكو يدخل للقلب فييسع ....  Positive

In [ ]:
# Append df2_selected to df1
appended_df = pd.concat([df1, df2_selected], axis=0, ignore_index=True)

# Save the appended dataframe to a CSV file
appended_df.to_csv('datasets/sentences/2_darija_ar_sentences.csv', index=False)

# Display the shape and the first few rows of the appended dataframe
print(f"Shape of appended dataframe: {appended_df.shape}")
print(appended_df.head())

Shape of appended dataframe: (56289, 2)
                              darija_ar Sentiment
0      هوما مخبّين شي حاجة, أنا متيقّن!       NaN
1    باينا هوما تايحاولو إبقاو مبرّدين.       NaN
2  لوطيلات مابايناش فيهوم مريحين بزّاف.       NaN
3         غالبا غايجرّيو عليه من لخدمة!       NaN
4                      طبعا راه مكتاءب!       NaN

### Dataset 2

In [ ]:
df1 = pd.read_csv('datasets/sentences/2_darija_ar_sentences.csv')
df2 = pd.read_csv('datasets/sentences/MAC corpus.csv')

In [ ]:
print(df2.shape)
print(df2.info())
df2.head()

(18087, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18087 entries, 0 to 18086
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tweets  18084 non-null  object
 1   type    18087 non-null  object
 2   class   18087 non-null  object
dtypes: object(3)
memory usage: 424.0+ KB
None

                                         tweets      type      class
0                     ماهي آرائكم متتبعي الكرام   neutral   standard
1                  عبقرية المدرب وروعة اللاعبين  positive   standard
2                        أمة عربية واحدة خالدة   positive   standard
3  عاد إليكم من جديد وأخيرا درت جيم لهاد الصفحة   neutral  dialectal
4                      الله يخلف عليك سيدي محمد  positive  dialectal

In [ ]:
df2[df2['class'] == 'dialectal'].value_counts().sum()

5461

In [ ]:
df2_selected = df2[df2['class'] == 'dialectal'][['tweets', 'type']]
df2_selected.rename(columns={
    'tweets': 'darija_ar',
    'type': 'Sentiment'
}, inplace=True)

In [ ]:
import pandas as pd

def append_and_save(df1, df2, save_path):
    """
    Appends two dataframes and saves the resulting dataframe to a CSV file.

    Parameters:
    - df1 (pd.DataFrame): The first dataframe.
    - df2 (pd.DataFrame): The second dataframe to append to the first.
    - save_path (str): Path to save the appended dataframe as a CSV file.

    Returns:
    - pd.DataFrame: The appended dataframe.
    """
    # Append df2 to df1
    appended_df = pd.concat([df1, df2], axis=0, ignore_index=True)

    # Save the appended dataframe to the specified path
    appended_df.to_csv(save_path, index=False)

    # Print the shape and first few rows of the appended dataframe
    print(f"Shape of appended dataframe: {appended_df.shape}")
    print(appended_df.head())

    return appended_df

In [ ]:
append_and_save(df1, df2_selected, 'datasets/sentences/3_darija_ar_sentences.csv')

Shape of appended dataframe: (61753, 2)
                              darija_ar Sentiment
0      هوما مخبّين شي حاجة, أنا متيقّن!       NaN
1    باينا هوما تايحاولو إبقاو مبرّدين.       NaN
2  لوطيلات مابايناش فيهوم مريحين بزّاف.       NaN
3         غالبا غايجرّيو عليه من لخدمة!       NaN
4                      طبعا راه مكتاءب!       NaN

                                  darija_ar Sentiment
0          هوما مخبّين شي حاجة, أنا متيقّن!       NaN
1        باينا هوما تايحاولو إبقاو مبرّدين.       NaN
2      لوطيلات مابايناش فيهوم مريحين بزّاف.       NaN
3             غالبا غايجرّيو عليه من لخدمة!       NaN
4                          طبعا راه مكتاءب!       NaN
...                                     ...       ...
61748     ريالية و افتخر و نعلي راسي الفوق   positive
61749                           ماكاين مشكل  positive
61750                      سمح ليا ماقصدتش   positive
61751                الله يكمل عليها بالخير  positive
61752                      يمكن و الله اعلم   neutral

[61753 rows x 2 columns]

### Dataset 3

In [ ]:
df1 = pd.read_csv('datasets/sentences/3_darija_ar_sentences.csv')

In [ ]:
df2 = pd.read_csv('datasets/sentences/AR_DATA_CLEANED.text', delimiter="\t", encoding='utf-8')

In [ ]:
print(df2.shape)
print(df2.info())
df2.head()

(11689, 1)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11689 entries, 0 to 11688
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    11689 non-null  object
dtypes: object(1)
memory usage: 91.4+ KB
None

                                                text
0           ييه وداك الدري لي كيبغي امينه شطرا ليه💀💔
1                                         يوييو 😂😂😂😂
2  يومين وانا نتبع فى أخبار ريان حتى آخر دقيقة فر...
3  يومكم سعيد، أهلا بكم أعزائي الكرام على المدونة...
4  يوم لن ينسى في تاريخنا كمغاربة كانت ولازالت صد...

In [ ]:
df2.rename(columns={'text': 'darija_ar'}, inplace=True)

In [ ]:
append_and_save(df1, df2, 'datasets/sentences/4_darija_ar_sentences.csv')

Shape of appended dataframe: (73442, 2)
                              darija_ar Sentiment
0      هوما مخبّين شي حاجة, أنا متيقّن!       NaN
1    باينا هوما تايحاولو إبقاو مبرّدين.       NaN
2  لوطيلات مابايناش فيهوم مريحين بزّاف.       NaN
3         غالبا غايجرّيو عليه من لخدمة!       NaN
4                      طبعا راه مكتاءب!       NaN

                                               darija_ar Sentiment
0                       هوما مخبّين شي حاجة, أنا متيقّن!       NaN
1                     باينا هوما تايحاولو إبقاو مبرّدين.       NaN
2                   لوطيلات مابايناش فيهوم مريحين بزّاف.       NaN
3                          غالبا غايجرّيو عليه من لخدمة!       NaN
4                                       طبعا راه مكتاءب!       NaN
...                                                  ...       ...
73437                    اOMG جبيتها والله حتا زوينة 🎉👏👏       NaN
73438  ا عباد الله هاد صفاء راها غزالة من ديما ماشي غ...       NaN
73439                              ا جزاء  بل ا نهاية😭😭😭       NaN
73440                               ا تش اااا رياح 😂😂😂😂😂       NaN
73441  ٱه ياقلبي ايش هالظلم. ومن ام ...يا الله.  ياار...       NaN

[73442 rows x 2 columns]

### Dataset 4

In [ ]:
df1 = pd.read_csv('datasets/sentences/4_darija_ar_sentences.csv')
df2 = pd.read_csv('datasets/sentences/train.csv')
df3 = pd.read_csv('datasets/sentences/test.csv')

In [ ]:
print(df2.shape)
print(df2.info())
df2.head()

(6419, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6419 entries, 0 to 6418
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  6419 non-null   int64
 1   comment     6419 non-null   object
 2   off         6419 non-null   int64
dtypes: int64(2), object(1)
memory usage: 150.6+ KB
None

   Unnamed: 0                                            comment  off
0        2908  فنانين الكبت والفساد .عقلية جنسية لا غير. العف...    1
1        1055  الدعارة هربت منها في المحمدية و سكنت في بوزنيق...    1
2         181                       كون غير خريتي و مدرتيش هادشي    1
3        4313  لا حول ولا قوة الا بالله العلي العظيم لا حول و...    0
4         228  الله يرحم الوالدين عندي مشكل كبيييير و محتاجة ...    0

In [ ]:
df2 = df2[['comment', 'off']]
df2['off'] = df2['off'].apply(lambda x: 'positive' if x == 1 else np.NaN)
df2.head()

                                             comment       off
0  فنانين الكبت والفساد .عقلية جنسية لا غير. العف...  positive
1  الدعارة هربت منها في المحمدية و سكنت في بوزنيق...  positive
2                       كون غير خريتي و مدرتيش هادشي  positive
3  لا حول ولا قوة الا بالله العلي العظيم لا حول و...       NaN
4  الله يرحم الوالدين عندي مشكل كبيييير و محتاجة ...       NaN

In [ ]:
print(df3.shape)
print(df3.info())
df3.head()

(1605, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1605 entries, 0 to 1604
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1605 non-null   int64
 1   comment     1605 non-null   object
 2   off         1605 non-null   int64
dtypes: int64(2), object(1)
memory usage: 37.7+ KB
None

   Unnamed: 0                                            comment  off
0        6139                      تبهديل تسؤلو البنات في الشارع    1
1        3447  انا مستعد بي مسعدة بسيطة في وجه اللة ربي يادير...    0
2        6844                لاحول ولاقوة الا بالله العلي العظيم    0
3        2512  حتى هاد العائلة لي جالس وسط منهوم خص يدلمهوم ا...    1
4        2000  لا حول ولا قوة الا بالله اش هذا المستوى اصلا ر...    1

In [ ]:
df3 = df3[['comment', 'off']]
df3['off'] = df3['off'].apply(lambda x: 'positive' if x == 1 else np.NaN)
df3.head()

                                             comment       off
0                      تبهديل تسؤلو البنات في الشارع  positive
1  انا مستعد بي مسعدة بسيطة في وجه اللة ربي يادير...       NaN
2                لاحول ولاقوة الا بالله العلي العظيم       NaN
3  حتى هاد العائلة لي جالس وسط منهوم خص يدلمهوم ا...  positive
4  لا حول ولا قوة الا بالله اش هذا المستوى اصلا ر...  positive

In [ ]:
df2.rename(columns={'comment': 'darija_ar', 'off': 'Sentiment'}, inplace=True)
df3.rename(columns={'comment': 'darija_ar', 'off': 'Sentiment'}, inplace=True)

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6419 entries, 0 to 6418
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   darija_ar  6419 non-null   object
 1   Sentiment  3416 non-null   object
dtypes: object(2)
memory usage: 100.4+ KB

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1605 entries, 0 to 1604
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   darija_ar  1605 non-null   object
 1   Sentiment  888 non-null    object
dtypes: object(2)
memory usage: 25.2+ KB

In [ ]:
append_and_save(df2, df3, 'datasets/sentences/5_darija_ar_sentences.csv')

Shape of appended dataframe: (8024, 2)
                                           darija_ar Sentiment
0  فنانين الكبت والفساد .عقلية جنسية لا غير. العف...  positive
1  الدعارة هربت منها في المحمدية و سكنت في بوزنيق...  positive
2                       كون غير خريتي و مدرتيش هادشي  positive
3  لا حول ولا قوة الا بالله العلي العظيم لا حول و...       NaN
4  الله يرحم الوالدين عندي مشكل كبيييير و محتاجة ...       NaN

                                              darija_ar Sentiment
0     فنانين الكبت والفساد .عقلية جنسية لا غير. العف...  positive
1     الدعارة هربت منها في المحمدية و سكنت في بوزنيق...  positive
2                          كون غير خريتي و مدرتيش هادشي  positive
3     لا حول ولا قوة الا بالله العلي العظيم لا حول و...       NaN
4     الله يرحم الوالدين عندي مشكل كبيييير و محتاجة ...       NaN
...                                                 ...       ...
8019                   لي جا من عند بيمو اخبط لايك 😹😹😹😹       NaN
8020           ونتساءل لمادا الله ارسل لنا فيروس كورونا  positive
8021  خانزة كيلوط وا الرويجل سير دير الرقية نصحك هاد...  positive
8022                                سير الله يعفو اعليك       NaN
8023  عندما تقومين بضرب أحدهم وبكلام غير لائق وتكتشف...  positive

[8024 rows x 2 columns]

In [ ]:
df2 = pd.read_csv('datasets/sentences/5_darija_ar_sentences.csv')

In [ ]:
append_and_save(df1, df2, 'datasets/sentences/5_darija_ar_sentences.csv')

Shape of appended dataframe: (79861, 2)
                              darija_ar Sentiment
0      هوما مخبّين شي حاجة, أنا متيقّن!       NaN
1    باينا هوما تايحاولو إبقاو مبرّدين.       NaN
2  لوطيلات مابايناش فيهوم مريحين بزّاف.       NaN
3         غالبا غايجرّيو عليه من لخدمة!       NaN
4                      طبعا راه مكتاءب!       NaN

                                               darija_ar Sentiment
0                       هوما مخبّين شي حاجة, أنا متيقّن!       NaN
1                     باينا هوما تايحاولو إبقاو مبرّدين.       NaN
2                   لوطيلات مابايناش فيهوم مريحين بزّاف.       NaN
3                          غالبا غايجرّيو عليه من لخدمة!       NaN
4                                       طبعا راه مكتاءب!       NaN
...                                                  ...       ...
79856                                 هدى  جمعاك شعر كحل       NaN
79857                تفو.. على أغنية زملاوية بحال مولاها  positive
79858  كون خرجات ها.ي كالت انا كنشطح كون بان ليك مساع...  positive
79859                                       الفديو زوين.       NaN
79860  مسكينة هدا ام الله ياكوان معها مسكينة يارب عفو...       NaN

[79861 rows x 2 columns]

### Dataset 5

In [ ]:
df1 = pd.read_csv('datasets/sentences/5_darija_ar_sentences.csv')
df2 = pd.read_table('datasets/sentences/sentences.txt')

In [ ]:
print(df2.shape)
print(df2.info())
df2.head()

(7213, 1)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7213 entries, 0 to 7212
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    7213 non-null   object
dtypes: object(1)
memory usage: 56.5+ KB
None

                                                text
0  ناس بداو تيتباكاو وبديت تنهدر ب نفعل بحال إلى ...
1  ناس بداو تيتباكاو وبديت تنهدر ب نفعل بحال إلى ...
2  بكيت والناس كلهم سكتو وانا جاني لعجب فراسي بحا...
3  ناض كلشي كيسلم عليا أو كيهدرو معايا نص بكى ونص...
4        تعردنا لعشا و كان لعشا كافي لكلشي المعرودين

In [ ]:
df2.rename(columns={'text': 'darija_ar'}, inplace=True)

In [ ]:
append_and_save(df1, df2, 'datasets/sentences/6_darija_ar_sentences.csv')

Shape of appended dataframe: (87074, 2)
                              darija_ar Sentiment
0      هوما مخبّين شي حاجة, أنا متيقّن!       NaN
1    باينا هوما تايحاولو إبقاو مبرّدين.       NaN
2  لوطيلات مابايناش فيهوم مريحين بزّاف.       NaN
3         غالبا غايجرّيو عليه من لخدمة!       NaN
4                      طبعا راه مكتاءب!       NaN

                                  darija_ar Sentiment
0          هوما مخبّين شي حاجة, أنا متيقّن!       NaN
1        باينا هوما تايحاولو إبقاو مبرّدين.       NaN
2      لوطيلات مابايناش فيهوم مريحين بزّاف.       NaN
3             غالبا غايجرّيو عليه من لخدمة!       NaN
4                          طبعا راه مكتاءب!       NaN
...                                     ...       ...
87069                       واش باقي ا محمد       NaN
87070        يلاه السلام عليكم في أمان الله       NaN
87071        يلاه السلام عليكم في أمان الله       NaN
87072        تيقني هو شاب غزال متقي و تيصلي       NaN
87073           كون كانت قرايت ف الليل هكدا       NaN

[87074 rows x 2 columns]

### Dataset 6

In [ ]:
df1 = pd.read_csv('datasets/sentences/5_darija_ar_sentences.csv')
df2 = pd.read_csv('datasets/sentences/headline train (1).csv')
df3 = pd.read_csv('datasets/sentences/headline test (1).csv')
df4 = pd.read_csv('datasets/sentences/healine validation.csv')

In [ ]:
print(df2.shape)
print(df2.info())
df2.head()

(139288, 1)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139288 entries, 0 to 139287
Data columns (total 1 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   headline  139288 non-null  object
dtypes: object(1)
memory usage: 1.1+ MB
None

                                            headline
0  برلمانيين من حزب الحمامة قلبوها بونيا قبل انتخ...
1     حكم ضد وزارة اعمارة بتعويض قدره 13 مليار لشركة
2  مغرب آنتيليجانس: المغرب لي عارض مشاركة إسبانيا...
3      جلسة خاصة بين مدرب الأهلي ومهاجم الأسود أزارو
4  اعتقال مهاجم الريال رونالدو في فرنسا… وها علاش...

In [ ]:
df2.rename(columns={'headline': 'darija_ar'}, inplace=True)
df3.rename(columns={'headline': 'darija_ar'}, inplace=True)
df4.rename(columns={'headline': 'darija_ar'}, inplace=True)

In [ ]:
appended_df = pd.concat([df2, df3, df4], axis=0, ignore_index=True)

# Display the shape and the first few rows of the appended dataframe
print(f"Shape of appended dataframe: {appended_df.shape}")
print(appended_df.head())

Shape of appended dataframe: (158282, 1)
                                           darija_ar
0  برلمانيين من حزب الحمامة قلبوها بونيا قبل انتخ...
1     حكم ضد وزارة اعمارة بتعويض قدره 13 مليار لشركة
2  مغرب آنتيليجانس: المغرب لي عارض مشاركة إسبانيا...
3      جلسة خاصة بين مدرب الأهلي ومهاجم الأسود أزارو
4  اعتقال مهاجم الريال رونالدو في فرنسا… وها علاش...

In [ ]:
append_and_save(df1, appended_df, 'datasets/sentences/7_darija_ar_sentences.csv')

Shape of appended dataframe: (238143, 2)
                              darija_ar Sentiment
0      هوما مخبّين شي حاجة, أنا متيقّن!       NaN
1    باينا هوما تايحاولو إبقاو مبرّدين.       NaN
2  لوطيلات مابايناش فيهوم مريحين بزّاف.       NaN
3         غالبا غايجرّيو عليه من لخدمة!       NaN
4                      طبعا راه مكتاءب!       NaN

                                                darija_ar Sentiment
0                        هوما مخبّين شي حاجة, أنا متيقّن!       NaN
1                      باينا هوما تايحاولو إبقاو مبرّدين.       NaN
2                    لوطيلات مابايناش فيهوم مريحين بزّاف.       NaN
3                           غالبا غايجرّيو عليه من لخدمة!       NaN
4                                        طبعا راه مكتاءب!       NaN
...                                                   ...       ...
238138  ومن الحب ما قتل.. هندي انتاحر في لايف على “فيس...       NaN
238139  الصبار:الإعدام عقوبة قاسية وبربرية والله وحده ...       NaN
238140  التزاني أستاذ القانون الدولي لـ”كَود”: قطع الع...       NaN
238141   127 مرشح جزائري لخلافة بوتفليقة على كرسي الجزائر       NaN
238142  الجزاير تاهما تزادت عندهم عمليات الحريكَـ و كا...       NaN

[238143 rows x 2 columns]

### Dataset 7

In [ ]:
df1 = pd.read_csv('datasets/sentences/7_darija_ar_sentences.csv')
df2 = pd.read_csv('datasets/sentences/texts_data.csv', on_bad_lines='skip', sep='\t')
df3 = pd.read_csv('datasets/sentences/texts_dev.csv', on_bad_lines='skip', sep='\t')

In [ ]:
print(df2.shape)
print(df2.info())
df2.head()

(2281, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2281 entries, 0 to 2280
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   wav       2281 non-null   object
 1   words     2281 non-null   object
 2   duration  2281 non-null   float64
dtypes: float64(1), object(2)
memory usage: 53.6+ KB
None

,wav,words,duration
0,2d95831a-469f-425b-b084-c988e07c37fa.wav,قديم وتسجيل للعمال اسباب وجود يا غبي ادري في ا...,5.629410
1,5017d025-7ad7-4184-a8cf-a79d702cefb2.wav,بطاقه دوز محل الساعه,3.394490
2,ebd17ddf-56ee-4e16-a80b-87acccd9a39f.wav,متى يعطى مؤتمر الجزيره الخضراء الحق الى فرنسا ...,5.701973
3,79763c3e-94f8-45fb-ad0b-c18cc636a085.wav,عندك موس عافاك؟,1.300000
4,86bf297a-0a21-4789-9a55-f9eb93196965.wav,دفع ايجار,2.909667

In [ ]:
df2.rename(columns={'words': 'darija_ar'}, inplace=True)
df3.rename(columns={'words': 'darija_ar'}, inplace=True)

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 456 entries, 0 to 455
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   wav        456 non-null    object
 1   darija_ar  456 non-null    object
 2   duration   456 non-null    float64
dtypes: float64(1), object(2)
memory usage: 10.8+ KB

In [ ]:
df2 = df2.drop(columns=['wav', 'duration'])
df3 = df3.drop(columns=['wav', 'duration'])

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2281 entries, 0 to 2280
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   darija_ar  2281 non-null   object
dtypes: object(1)
memory usage: 17.9+ KB

In [ ]:
df3.head()

                                    darija_ar
0                         استمرار طلب الايبان
1                              19 فبراير 1681
2     وكن بعد الناس يصوموا وانا معصبه ولا شيء
3  هل يجوز العقوبه دي المستشفى العسكري بحلاته
4                        شويات الف مبروك كامل

In [ ]:
appended_df = pd.concat([df2, df3], axis=0, ignore_index=True)

# Display the shape and the first few rows of the appended dataframe
print(f"Shape of appended dataframe: {appended_df.shape}")
print(appended_df.head())

Shape of appended dataframe: (2737, 1)
                                           darija_ar
0  قديم وتسجيل للعمال اسباب وجود يا غبي ادري في ا...
1                               بطاقه دوز محل الساعه
2  متى يعطى مؤتمر الجزيره الخضراء الحق الى فرنسا ...
3                                    عندك موس عافاك؟
4                                          دفع ايجار

In [ ]:
append_and_save(df1, appended_df, 'datasets/sentences/8_darija_ar_sentences.csv')

Shape of appended dataframe: (240880, 2)
                              darija_ar Sentiment
0      هوما مخبّين شي حاجة, أنا متيقّن!       NaN
1    باينا هوما تايحاولو إبقاو مبرّدين.       NaN
2  لوطيلات مابايناش فيهوم مريحين بزّاف.       NaN
3         غالبا غايجرّيو عليه من لخدمة!       NaN
4                      طبعا راه مكتاءب!       NaN

                                                darija_ar Sentiment
0                        هوما مخبّين شي حاجة, أنا متيقّن!       NaN
1                      باينا هوما تايحاولو إبقاو مبرّدين.       NaN
2                    لوطيلات مابايناش فيهوم مريحين بزّاف.       NaN
3                           غالبا غايجرّيو عليه من لخدمة!       NaN
4                                        طبعا راه مكتاءب!       NaN
...                                                   ...       ...
240875                                               اخوك       NaN
240876  ومع وليش نتنازل على الدين ديالى ولا الاخلاق من...       NaN
240877                                            يا معلم       NaN
240878                                      اسمي عبد الله       NaN
240879                                          ضعيفه جدا       NaN

[240880 rows x 2 columns]

# Darija Stop Words

### Lib's

In [ ]:
import pandas as pd
import numpy as np

### Dataset 1

In [ ]:
df1 = pd.read_csv('datasets/stop-words/darija_stop_words.csv')

In [ ]:
print(df1.shape)
print(df1.info())
df1.tail()

(2112, 1)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2112 entries, 0 to 2111
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   stop_words  2112 non-null   object
dtypes: object(1)
memory usage: 16.6+ KB
None

      stop_words
2107     كاين دك
2108     كاين شي
2109  ما كاين ما
2110    بزاف حيت
2111   بزاف شوية

In [ ]:
df1.duplicated().sum()

1088

In [ ]:
df1.drop_duplicates(inplace=True)

In [ ]:
df1.to_csv('datasets/stop-words/1_darija_stop_words.csv', index=False)

# Darija sentiment Words

### Lib's

In [ ]:
import pandas as pd
import numpy as np

### Dataset 1

In [ ]:
df1 = pd.read_csv('datasets/words/MAC lexicon.csv')
df2 = pd.read_csv('datasets/words/emotions.csv')
df3 = pd.read_csv('datasets/words/words.csv')

In [ ]:
print(df1.shape)
print(df1.info())
df1.head()

(30014, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30014 entries, 0 to 30013
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Token   30014 non-null  object
 1   Type    30014 non-null  object
dtypes: object(2)
memory usage: 469.1+ KB
None

      Token    Type
0     وكاين  neutre
1     بحالي  neutre
2        لي  neutre
3      عارف  neutre
4  ماغايجيه  neutre

In [ ]:
print(df2.shape)
print(df2.info())
df2.head()

(60, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   n1         60 non-null     object
 1   n2         40 non-null     object
 2   n3         18 non-null     object
 3   n4         9 non-null      object
 4   darija_ar  60 non-null     object
 5   eng        60 non-null     object
dtypes: object(6)
memory usage: 2.9+ KB
None

       n1       n2       n3   n4 darija_ar         eng
0   9ala9   t9li9a    qalaq  NaN       قلق       worry
1  tbrziT  tberziT  tbarziT  NaN    تبرزيط   annoyance
2  ghaDab      NaN      NaN  NaN       غضب       anger
3  nachaT  nachaaT      NaN  NaN      نشاط   amusement
4  9oboul    9obol   qoboul  NaN      قبول  acceptance

In [ ]:
print(df3.shape)
print(df3.info())
df3.head()

(618, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 618 entries, 0 to 617
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Word    618 non-null    object
 1   Label   618 non-null    object
dtypes: object(2)
memory usage: 9.8+ KB
None

    Word Label
0   زوين   pos
1  فرحان   pos
2   ناشط   pos
3   رائع   pos
4   سعيد   pos

In [ ]:
df1.rename(columns={'Token': 'word', 'Type': 'label'}, inplace=True)
df2.rename(columns={'darija_ar': 'word'}, inplace=True)
df2.drop(columns=['n1', 'n2', 'n3', 'n4', 'eng'], inplace=True)
df3.rename(columns={'Word': 'word', 'Label': 'label'}, inplace=True)

In [ ]:
print(df1.head(), '\n')
print(df2.head(), '\n')
print(df3.head())

       word   label
0     وكاين  neutre
1     بحالي  neutre
2        لي  neutre
3      عارف  neutre
4  ماغايجيه  neutre

     word
0     قلق
1  تبرزيط
2     غضب
3    نشاط
4    قبول

    word label
0   زوين   pos
1  فرحان   pos
2   ناشط   pos
3   رائع   pos
4   سعيد   pos

In [ ]:
df2['label'] = np.NaN

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   word    60 non-null     object
 1   label   0 non-null      float64
dtypes: float64(1), object(1)
memory usage: 1.1+ KB

In [ ]:
appended_df = pd.concat([df1, df2, df3], axis=0, ignore_index=True)

# Display the shape and the first few rows of the appended dataframe
print(f"Shape of appended dataframe: {appended_df.shape}")
print(appended_df.head())

Shape of appended dataframe: (30692, 2)
       word   label
0     وكاين  neutre
1     بحالي  neutre
2        لي  neutre
3      عارف  neutre
4  ماغايجيه  neutre

In [ ]:
appended_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30692 entries, 0 to 30691
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   word    30692 non-null  object
 1   label   30632 non-null  object
dtypes: object(2)
memory usage: 479.7+ KB

In [ ]:
appended_df.to_csv('datasets/words/1_darija_ar_words.csv', index=False)